In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('SPY_Statistics.csv', encoding='unicode_escape', low_memory=True) 

df.head(10)

        Date     Calls      Puts      SPXL
0   1/3/2017  1.400000 -1.000000  0.017167
1   1/4/2017 -0.695652 -0.333333 -0.002312
2   1/5/2017 -0.100000 -0.960000  0.010551
3   1/6/2017 -0.840000  0.092308 -0.010646
4   1/9/2017 -0.566667 -0.344828  0.000000
5  1/10/2017  0.676471 -1.000000  0.008489
6  1/11/2017 -0.857143  0.440000 -0.006434
7  1/12/2017  1.028571 -1.000000  0.005550
8  1/13/2017 -0.903226  0.711111 -0.008903
9  1/17/2017 -0.275862 -1.000000  0.005291

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 4 columns):
Date     764 non-null object
Calls    764 non-null float64
Puts     764 non-null float64
SPXL     764 non-null float64
dtypes: float64(3), object(1)
memory usage: 24.0+ KB

In [3]:
# 0 put up
# 1 call up
# 2 both down

result = []
for i, row in df.iterrows():
    c,p = row[1],row[2]
    if c < 0 and p >= 0:
        result.append(0)
    elif c >= 0 and p < 0.0000001:
        result.append(1)
    elif c <= 0 and p <= 0:
        result.append(2)


df['result'] = result

In [46]:
# num = number of days ago
def set_days_ago(df,num, snp = False):
    # drop first num of rows
    df1 = df.drop(df.index[:num])

    # list of the list = [10day_ago,9....1]
    result_list = []
    snp_list = []
    for i in range(num):
        result_list.append([])
        snp_list.append([])
    
    for i, row in df.iterrows():
        if(i < num):
            continue
            
        list1 = df['result'][i-num:i]
        for j,item in enumerate(list1):
            result_list[j].append(item)
        if(snp):    
            list2 = df['SPXL'][i-num:i]
            for j,item in enumerate(list2):
                snp_list[j].append(item)

    names_res = []
    names_snp = []
    for i in range(num):
        s = str(num-i)
        s += 'days_ago'
        names_res.append(s)
        s2 = 'snp_' + str(num-i) + 'days_ago'
        names_snp.append(s2)

    for i,n in enumerate(names_res):
        df1[n]= result_list[i]
    if(snp): 
        for i,n in enumerate(names_snp):
            df1[n]= snp_list[i]
            
        
    return df1

In [47]:
new_df = set_days_ago(df,10)

new_df.head(10)

,Date,Calls,Puts,SPXL,result,10days_ago,9days_ago,8days_ago,7days_ago,6days_ago,5days_ago,4days_ago,3days_ago,2days_ago,1days_ago
10,1/18/2017,-0.580645,0.220339,-0.010828,0,1,2,2,0,2,1,0,1,0,2
11,1/19/2017,-1.000000,-1.000000,0.010099,2,2,2,0,2,1,0,1,0,2,0
12,1/20/2017,-0.687500,0.067797,-0.008070,0,2,0,2,1,0,1,0,2,0,2
13,1/23/2017,1.956522,-0.876923,0.019694,1,0,2,1,0,1,0,2,0,2,0
14,1/24/2017,3.868421,-1.000000,0.024078,1,2,1,0,1,0,2,0,2,0,1
15,1/25/2017,-0.483871,-0.303571,-0.002206,2,1,0,1,0,2,0,2,0,1,1
16,1/26/2017,-1.000000,-0.800000,-0.002599,2,0,1,0,2,0,2,0,1,1,2
17,1/27/2017,-0.815789,0.862069,-0.018029,0,1,0,2,0,2,0,1,1,2,2
18,1/30/2017,-0.645161,-0.406780,-0.002670,2,0,2,0,2,0,1,1,2,2,0
19,1/31/2017,-1.000000,-0.948718,0.000895,2,2,0,2,0,1,1,2,2,0,2

In [48]:
X_norm = new_df.drop(['Date','Calls','Puts','SPXL','result'], axis=1)
y = new_df['result']

#normalize the data
#X_norm = -1 + ((X-X.min())*2/(X.max()-X.min()))

X_norm.head(10)

,10days_ago,9days_ago,8days_ago,7days_ago,6days_ago,5days_ago,4days_ago,3days_ago,2days_ago,1days_ago
10,1,2,2,0,2,1,0,1,0,2
11,2,2,0,2,1,0,1,0,2,0
12,2,0,2,1,0,1,0,2,0,2
13,0,2,1,0,1,0,2,0,2,0
14,2,1,0,1,0,2,0,2,0,1
15,1,0,1,0,2,0,2,0,1,1
16,0,1,0,2,0,2,0,1,1,2
17,1,0,2,0,2,0,1,1,2,2
18,0,2,0,2,0,1,1,2,2,0
19,2,0,2,0,1,1,2,2,0,2

In [49]:
print('y:')
unique_elements, counts_elements = np.unique(y, return_counts=True)
for i in range(3):
    print(unique_elements[i],':',counts_elements[i])
    
# 0 put up
# 1 call up
# 2 both down

y:
0 : 183
1 : 201
2 : 370

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_norm, y, test_size=0.10, random_state=42, stratify=y)
print('X_train shape:',X_train.shape)
print('X_test shape:',X_test.shape)
print('Y_train shape:',Y_train.shape)
print('Y_test shape:',Y_test.shape)

X_train shape: (678, 10)
X_test shape: (76, 10)
Y_train shape: (678,)
Y_test shape: (76,)

In [51]:
%%time
from sklearn.linear_model import LogisticRegression as SKLogisticRegression
from sklearn.metrics import accuracy_score

lr_sk = SKLogisticRegression(solver='liblinear')

lr_sk.fit(X_train,Y_train)
yhat = lr_sk.predict(X_test)

print('Accuracy of: ',accuracy_score(Y_test,yhat))

print(yhat)

Accuracy of:  0.4605263157894737
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0
 2 2]
Wall time: 8 ms

In [52]:
from scipy.special import expit
from sklearn.metrics import accuracy_score
import sys

class MultiLayerPerceptronBase(object):
    def __init__(self, n_hidden=30,
                 C=0.0, epochs=50, eta=0.00001, random_state=None, layers = 3):
        np.random.seed(random_state)
        self.n_hidden = n_hidden
        self.l2_C = C
        self.epochs = epochs
        self.eta = eta
        self.layers = layers
        
    @staticmethod
    def _encode_labels(y):
        """Encode labels into one-hot representation"""
        onehot = pd.get_dummies(y).values.T 
        return onehot

    def _initialize_weights(self):
        """Initialize weights with small random numbers."""
        
        Ws = []

        rows = self.n_hidden
        cols = self.n_features_ + 1
        for i in range(self.layers - 1):
            num_elems = rows*cols
            W1 = np.random.uniform(-1.0, 1.0, size=num_elems)
            W1 = W1.reshape(rows, cols) # reshape to be W
            Ws.append(W1)
            cols = rows + 1
               
        
        W2_num_elems = (self.n_hidden + 1)*self.n_output_
        W2 = np.random.uniform(-1.0, 1.0, size=W2_num_elems)
        W2 = W2.reshape(self.n_output_, self.n_hidden + 1)
        Ws.append(W2)
        
        return Ws
    
    @staticmethod
    def _sigmoid(z):
        return expit(z)
    
    @staticmethod
    def _add_bias_unit(X, how='column'):
        """Add bias unit (column or row of 1s) to array at index 0"""
        if how == 'column':
            ones = np.ones((X.shape[0], 1))
            X_new = np.hstack((ones, X))
        elif how == 'row':
            ones = np.ones((1, X.shape[1]))
            X_new = np.vstack((ones, X))
        return X_new
    
    @staticmethod
    def _L2_reg(lambda_, Ws):
        """Compute L2-regularization cost"""
        # only compute for non-bias terms
        total = 0
        for w in Ws:
            total += np.mean(w[:, 1:] ** 2)
        
        return (lambda_/2.0) * np.sqrt(total)
    
    def _cost(self,A3,Y_enc,Ws):
        '''Get the objective function value'''
        cost = np.mean((Y_enc-A3)**2)
        L2_term = self._L2_reg(self.l2_C, Ws)
        return cost + L2_term
    

class MultiLayerPerceptron(MultiLayerPerceptronBase):
    def _feedforward(self, X, Ws):
        
        As = []
        Zs = []
        A = self._add_bias_unit(X.T, how='row')
        As.append(A)
        
        for i,w in enumerate(Ws):
            Z1 = w @ A
            Zs.append(Z1)
            A = self._sigmoid(Z1)
            if i != len(Ws) - 1: # not adding biasing for the last A
                A = self._add_bias_unit(A, how='row')
            As.append(A)
            
        return As, Zs
            
    
    def _get_gradient(self, As, Zs, Y_enc, Ws): 
        grads = []
        Vs = []
        
        # vectorized backpropagation
        V2 = -2*(Y_enc-As[-1])*As[-1]*(1-As[-1])
        Vs.append(V2)
        
        for i in range(len(As)-2,0,-1):
            if i != self.layers-1:
                # need to take off the bias
                V1 = (As[i]*(1-As[i]))*(Ws[i].T @ Vs[0][1:,:])
            else:
                V1 = As[i]*(1-As[i])*(Ws[i].T @ Vs[0])
            Vs.insert(0,V1) 
        
        lastV = len(Vs)-1
        for i,v in enumerate(Vs):
            if i != lastV:
                g = v[1:,:] @ As[i].T 
                grads.append(g)            
        
        grads.append(Vs[lastV] @ As[lastV].T)
        
        
        for i,w in enumerate(Ws):
            grads[i][:, 1:] += w[:, 1:] * self.l2_C

        return grads
    
    def predict(self, X):
        """Predict class labels"""
        As, _ = self._feedforward(X, self.Ws)        
        y_pred = np.argmax(As[-1], axis=0)
        return y_pred 
    
    
    def fit(self, X, y, print_progress=False):
        """ Learn weights from training data."""
        
        X_data, y_data = X.copy(), y.copy()
        
        Y_enc = self._encode_labels(y)
        
        # init weights and setup matrices
        self.n_features_ = X_data.shape[1]
        self.n_output_ = Y_enc.shape[0]
        self.Ws = self._initialize_weights()

        self.cost_ = []
        for i in range(self.epochs):

            if print_progress>0 and (i+1)%print_progress==0:
                sys.stderr.write('\rEpoch: %d/%d' % (i+1, self.epochs))
                sys.stderr.flush()

            # feedforward all instances
            As, Zs = self._feedforward(X_data,self.Ws)

            
            cost = self._cost(As[-1],Y_enc,self.Ws)
            self.cost_.append(cost)

            # compute gradient via backpropagation
            grads = self._get_gradient(As=As, Zs=Zs, Y_enc=Y_enc, Ws=self.Ws)
            
            for j,w in enumerate(self.Ws):
                self.Ws[j] -= self.eta * grads[j] 
            
    
        return self
    
class MLP_AdaM(MultiLayerPerceptron):
    def fit(self, X, y, print_progress=False):

        X_data, y_data = X.copy(), y.copy()
        
        Y_enc = self._encode_labels(y)
        
        # init weights and setup matrices
        self.n_features_ = X_data.shape[1]
        self.n_output_ = Y_enc.shape[0]
        self.Ws = self._initialize_weights()
        
        # initialize all the parameters 
        beta1 = 0.9
        beta2 = 0.999
        epsilon = 10**-8
        mt = []
        vt = []
        prev_mt = []
        prev_vt = []
        mt_hat = []
        vt_hat = []
        
        for w in self.Ws:
            prev_mt.append(np.zeros(w.shape))
            prev_vt.append(np.zeros(w.shape))

        self.cost_ = []
        for j in range(self.epochs):
            
            if print_progress>0 and (j+1)%print_progress==0:
                sys.stderr.write('\rEpoch: %d/%d' % (j+1, self.epochs))
                sys.stderr.flush()

            # feedforward all instances
            As, Zs = self._feedforward(X_data,self.Ws)
            
            cost = self._cost(As[-1],Y_enc,self.Ws)
            self.cost_.append(cost)

            # compute gradient via backpropagation
            grads = self._get_gradient(As=As, Zs=Zs, Y_enc=Y_enc, Ws=self.Ws)
            
            # calculate mt - grad momentum, vt - square grad momentum
            for i in range(len(prev_mt)):
                # for the first time just append, later update
                if j == 0:
                    mt.append(beta1 * prev_mt[i] + (1-beta1) * grads[i])
                    vt.append(beta2 * prev_vt[i] + (1-beta2) * ((grads[i])**2))
                    mt_hat.append(mt[i]/(1-beta1))
                    vt_hat.append(vt[i]/(1-beta2))
                else:
                    mt[i] = beta1 * prev_mt[i] + (1-beta1) * grads[i]
                    vt[i] = beta2 * prev_vt[i] + (1-beta2) * ((grads[i])**2)
                    mt_hat[i] = mt[i]/(1-(beta1**j))
                    vt_hat[i] = vt[i]/(1-(beta2**j))
                    
                self.Ws[i] -= self.eta*mt_hat[i]/(vt_hat[i]**0.5 + epsilon)
                
            #update prev mt,vt:
            for i in range(len(prev_vt)):
                prev_vt[i] = vt[i]
                prev_mt[i] = mt[i]
    
        return self

In [56]:
params = dict(n_hidden=10, 
              epochs=100, 
              eta=0.01, # larger eta since we using an adaptive technique
              random_state=1,
              layers = 20)

MLP_Adam = MLP_AdaM(**params)
MLP_Adam.fit(X_train, Y_train, print_progress=1)
yhat_AdaM = MLP_Adam.predict(X_test)

print('Test acc:',accuracy_score(Y_test,yhat_AdaM))

print(yhat)

Epoch: 100/100

Test acc: 0.4868421052631579
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0
 2 2]

In [57]:
# given data for april2
myinput = [2,0,2,1,2,1,0,1,0,0]
myinput = np.array(myinput).reshape((1,len(myinput)))

In [58]:
MLP_Adam = MLP_AdaM(**params)
MLP_Adam.fit(X_train, Y_train, print_progress=1)
yhat_AdaM = MLP_Adam.predict(myinput)

yhat_AdaM

Epoch: 100/100

array([2], dtype=int64)